export const HERO_ENDPOINT ='/hero'
export const SERVICES_ENDPOINT ='/services'
export const ABOUT_ENDPOINT ='/about'
export const SKILLS_ENDPOINT ='/skills'
export const PORTFOLIO_ENDPOINT ='/portfolio'
export const FACTS_ENDPOINT ='/facts'
export const TESTIMONIALS_ENDPOINT ='/testimonials'
export const CONTACT_ENDPOINT ='/contact'